require 'opal'
require 'opal/full'
require 'opal_ujs'
require 'opal-jquery'
require 'opal-haml'
require 'active_support'

require 'native'
require 'js'
require 'browser'
require 'browser/console'

require 'model'
require 'collection'
require 'component'
require 'controller'
require 'router'